### ISSUE TITLE
Improve accuracy of registered EventTypes' source

### ISSUE THREAD

**Issue by antoineco** [triggermesh/aws-event-sources#106]
The registration of the EventTypes supported by AWS Sources is delegated to the reconcilers. Currently those reconcilers do not do anything with the credentials from Source objects and merely pass them to the adapters in a shape that suits them (env var, reference to secret, ...).

One of the shortcomings of the current approach is that reconcilers can only register event types with a partial context.

Take the example of DynamoDB:
```console
$ kubectl get eventtypes.eventing.knative.dev
NAME        TYPE                         SOURCE                                         SCHEMA   BROKER    DESCRIPTION   READY   REASON
1b6034...   com.amazon.dynamodb.modify   aws:dynamodb:eu-central-1:table/sample-table            default                 True
9357f3...   com.amazon.dynamodb.remove   aws:dynamodb:eu-central-1:table/sample-table            default                 True
e1092d...   com.amazon.dynamodb.insert   aws:dynamodb:eu-central-1:table/sample-table            default                 True
```

The `source` field contains a _pseudo_ [ARN](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html), but not quite the actual ARN generated by AWS, which typically contains the account id as well (e.g. `arn:aws:dynamodb:eu-central-1:044455340429:table/sample-table`). Without this account id, **we could potentially have multiple AWS Services with the same name in different accounts** that will be registered with the exact same name in Kubernetes.

We should investigate whether the reconciler could instead make use of the credentials to retrieve _real_ ARNs, and surface them as the _source_ field in the EventTypes.

**Comment by antoineco** [comment]
I have an idea about how we could tackle this one.

I would hate to see the controller connecting to users' AWS accounts just for the sake of retrieving an account ID. It would make things harder to secure, and we would have to ensure the controller can read arbitrary Secrets, or get credentials via kube2iam.

Instead, how about we change our Sources' spec slightly and ask users to pass an `arn` instead of a combination of `region` + `resourceName` (table, stream, ... depending on the AWS service we're taking about). ARNs are great because they contain a lot of useful information for our sources, and they're easy to parse.

**Comment by sebgoa** [comment]
I suggest to check the serverless framework to see how the connect to various AWS services.

I am not 100% sure about the sensitivity of ARNs, can they be exposed publicly ?

**Comment by antoineco** [comment]
@sebgoa The issue here is not about connecting to AWS services, but about building a meaningful catalog of event types.

Without the account ID, you would end up with duplicates in case customers use the same name for a given service across multiple AWS accounts. Example:

"Antoine creates a DynamoDB source called _triggermesh-events_ in account 01234"
"Sébastien also creates a DynamoDB source called _triggermesh-events_ in account 04567"

Our DynamoDBs receive unrelated events. Yet, internally the TriggerMesh controller currently creates a single event type:
```
NAME        TYPE                         SOURCE                                       SCHEMA   BROKER    DESCRIPTION   READY   REASON
e1092d...   com.amazon.dynamodb.insert   aws:dynamodb:eu-central-1:table/triggermesh           default                 True
```

You can't tell both sources apart.

However, you can if you include an ID to tell them apart:

```
NAME        TYPE                         SOURCE                                              SCHEMA   BROKER    DESCRIPTION   READY   REASON
e1092d...   com.amazon.dynamodb.insert   aws:dynamodb:eu-central-1:01234:table/triggermesh            default                 True
e1092d...   com.amazon.dynamodb.insert   aws:dynamodb:eu-central-1:05678:table/triggermesh            default                 True
```

I believe it wouldn't be sensible to use ARNs, especially since we wouldn't expose them to the public. Those ARNs stay inside the cluster, just like any other information that the frontend currently uses to generate ContainerSources.

**Comment by odacremolbap** [comment]
:100: on this

If I'm not wrong we need to add a different `status.ceAttributes[*].source` value here, which might mean:

- exposing it at the adapter status
- gathering it at the controller and adding to the source status

What @sebgoa makes a lot of sense as long as the event registry is not multitenant. I think we need a new ticket for that despite the outcome of this one.

**Comment by sebgoa** [comment]
I am just wondering about the multi-tenancy indeed.

If the eventtype registry is cluster scoped, some users could see the ARN of other users in different namespaces.

**Comment by antoineco** [comment]
The registry is namespace-scoped, otherwise we would have to put a cross on it completely because users would be able to see each other's sources, ARN or not.

**Comment by sebgoa** [comment]
Good, so I would just spend 20 minutes looking at the serverless framework. They use ARN in their manifests, for example.

https://github.com/serverless/examples/blob/master/aws-node-dynamodb-backup/serverless.yml

I would just make sure exposing the account ID is not problematic

**Comment by antoineco** [comment]
I couldn't think about a scenario where having the account ID visible in the event type could be problematic since it's only "exposed" to the users themselves, who by definition _know_ their own account ID.

Google returned a few discussions on the topic (sorry for quoting StackExchange as if it was the ultimate source of truth 😊):

*
    > An AWS Account ID can be shared, when required.
    >
    > Like the documentation says, the main thing anyone can use your AWS Account Number for is to construct ARN's. For example, if I had an AWS Account which held an AWS Lambda function, and someone on another account, who I had explicitly granted permission to, wanted to manipulate it, they would use by account number in the ARN.
    >
    > -- https://security.stackexchange.com/a/192547/105952

*
    > Sharing AWS Account numbers is fairly safe among business partners. There is not much if anything that anyone can do with just the account number. To assume a role, the account number is required, but the authorizing account must also setup a trust relationship for the policy.
    >
    > -- https://stackoverflow.com/a/47586088/4716370

*
    > I'd say it should generally remain private. But you will need to provide it if you want to set up cross account access with a 3rd party.
    >
    > If you trust the 3rd party enough to set up cross-account access then it should be fine to provide them your account number.
    >
    > -- https://acloud.guru/forums/aws-certified-solutions-architect-professional/discussion/-KRUT9T6gFZ4Ebyv0hLp/my-aws-account-id-should-it-remain-private

**Comment by antoineco** [comment]
@sebgoa did you come up with a final decision regarding this? If identifying AWS event sources by their ARN is a no-go, do you have any other suggestion for uniquely identifying them?

**Comment by sebgoa** [comment]
Let's go with arn
