### ISSUE TITLE
CI: test PR's against merge of the branch

### ISSUE THREAD

**Issue by sameersbn** [triggermesh/aws-event-sources#119]
CircleCI shows test results on the PR branch and not against the prospective merge of the branch. 
Ideally we should be testing the prospective merge, but Circle CI does not offer this option/setting.

A quick workaround is to use the  [circleci-orb-ghpr ](https://github.com/NarrativeScience/circleci-orb-ghpr) orb functionality to prepare a merged base branch for running the tests.

ref: https://ideas.circleci.com/ideas/CCI-I-926

**Comment by sameersbn** [comment]
the last PR was reverted

**Comment by sameersbn** [comment]
the circle ci `build-tools-orb` has a command to  simulate the merging of the PR's branch into the target branch, it does not really test the merged commit though. Do you think it would be useful to add this merge test to our jobs?

**Comment by antoineco** [comment]
If it doesn't test what's the point? GitHub already has conflict detection.

**Comment by sameersbn** [comment]
that's what I was thinking too. I am not sure what purpose this serves when github blocks the merge when there are conflicts, comment on https://ideas.circleci.com/cloud-feature-requests/p/show-test-results-for-prospective-merge-of-a-github-pr says "PRs build should not run on the PR's branch HEAD commit but on the a "fictive" commit that simulates the merging of the PR's branch into the target branch" but my tests don't indicate this behaviour, maybe I am missing something.

**Comment by antoineco** [comment]
@antoineco I think we can close this because CircleCI doesn't have the feature we need?

**Comment by antoineco** [comment]
@sameersbn I think we can close this because CircleCI doesn't have the feature we need?
