### ISSUE TITLE
CI: Publish docker image step fails with "error checking push permissions"

### ISSUE THREAD

**Issue by antoineco** [triggermesh/aws-event-sources#133]
paging @sameersbn

**Comment by sameersbn** [comment]
This is the kaniko issue I was talking about.

**Comment by sameersbn** [comment]
https://github.com/GoogleContainerTools/kaniko/issues/1242 fix in https://github.com/GoogleContainerTools/kaniko/releases/tag/v0.22.0

**Comment by antoineco** [comment]
Cheers @sameersbn, thanks for the update!
