### ISSUE TITLE
Fix AWS Cognito source (Identity pools)

### ISSUE THREAD

**Issue by tzununbekov** [triggermesh/aws-event-sources#148]
test current AWS Cognito Identity Pool source, fix if needed or replace with User Pool source

**Comment by tzununbekov** [comment]
Couldn't make current AWS Cognito source working, ended up by replacing with new AWS CognitoUserPoolSource

**Comment by sebgoa** [comment]
I don't understand. We have a Cognito source already. Are you saying it does not work ? if yes we should fix it.

And/or are you saying that the CognitoUserPoolSource is a new source that does the same thing as the previous Cognito source ?

**Comment by tzununbekov** [comment]
I just needed to have an issue to reflect my work on AWS Cognito. Besides, after some investigation I had an impression that User Pool is more common case for AWS Cognito event source while Identity Pool requires either [AWS Mobile or JavaScript SDK](https://docs.aws.amazon.com/cognito/latest/developerguide/getting-started-with-identity-pools.html#install-the-mobile-or-javascript-sdk) to work with it. That is, until we figure out the flows to use AWS Cognito Identity Pool, I'd call User Poll our default AWS Cognito event source. Anyway, I'm sorry that I confused everyone with this issue

**Comment by antoineco** [comment]
Shall we take action and remove or rename the old source in that case?

**Comment by tzununbekov** [comment]
If we worry that Triggermesh users get confused by Cognito/CognitoUserPool sources, then I'd rename them, although I don't have a strong opinion about that
