### ISSUE TITLE
Source adapter set the same subject on every message

### ISSUE THREAD

**Issue by antoineco** [triggermesh/aws-event-sources#212]
Using `SenderId` as the subject was probably not the best idea, and it might be better not to set a subject at all.

**Comment by sebgoa** [comment]
this was required to be able to use the source with a Argo events Trigger. Finding a sane default and staying interoperable with Argo is a nice to have.

**Comment by antoineco** [comment]
I'm fine keeping _some_ value in the subject, but is has to make sense. It should be Argo's responsibility to be aligned with the CE spec:

![image](https://user-images.githubusercontent.com/3299086/101343796-d37daf00-3884-11eb-9819-74737b4215f0.png)

**Comment by sebgoa** [comment]
then let's drop it., I don't want to bike shed this

**Comment by sebgoa** [comment]
meaning: remove the subject and let's move on

**Comment by antoineco** [comment]
I opened https://github.com/argoproj/argo-events/issues/983

Like I said, I'm totally fine finding a subject field that is meaningful. I opened this issue because right now the subject is always set to the same value.

**Comment by antoineco** [comment]
This was tackled as a side effect of #267. Closing.
