### ISSUE TITLE
Howto use with http_proxy

### ISSUE THREAD

**Issue by davidkarlsen** [triggermesh/aws-event-sources#251]
How can I make the calls to AWS use a http proxy?

**Comment by antoineco** [comment]
@davidkarlsen this is not possible if you deploy sources using Kubernetes objects. However, if you run those event sources as your own containers, you could export the standard proxy environment variables in the container's environment (e.g. https://www.shellhacks.com/linux-proxy-server-settings-set-proxy-command-line/).

**Comment by davidkarlsen** [comment]
As in simply copying the generated deployment yaml, delete the custom resource, and reapply the saved and augmented deployment yaml? Or is there some other construct you have in mind?


Is it possible to make the crd (kind: AWSSQSSource) pass annotations to the spawned container for the integration - then I could make it inject an istio sidecar and I could make that take care of the proxying.

**Comment by antoineco** [comment]
We could think of doing that yes, as long as we're not trying to turn the CRD into a Pod spec.

Regarding Istio, have you thought about automatic injection at the namespace level for the time being, possibly using exceptions? https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#more-control-adding-exceptions

**Comment by davidkarlsen** [comment]
Unfortunately that does not seem like an option on openshift: https://docs.openshift.com/container-platform/4.6/service_mesh/v1x/prepare-to-deploy-applications-ossm.html#ossm-automatic-sidecar-injection_deploying-applications-ossm-v1x

**Comment by davidkarlsen** [comment]
Closing in favour of https://github.com/triggermesh/aws-event-sources/issues/252
