### ISSUE TITLE
Outbound events / Sink?

### ISSUE THREAD

**Issue by davidkarlsen** [triggermesh/aws-event-sources#257]
Do you support Sink's https://knative.dev/docs/eventing/sink/.
My use-case is:
- a Knative service which gets triggered by subscribing to SQSevents (which works very well - thanks to this project)
- as a result of having been triggered I want to publish an event to SNS, and would like to do this using the same concept of cloudevents and "binding" to an AWS service, in this case SNS. i.e. sending an outbound event.

**Comment by antoineco** [comment]
We do but right now their source code is closed. Those sinks (we call them "target") are available at http://cloud.triggermesh.io only for the time being.

cc. @sebgoa @odacremolbap and @cab105  FYI

**Comment by davidkarlsen** [comment]
bummer, is there any plan to open this, or is this a closed-source / strictly commercial offering atm?

**Comment by cab105** [comment]
As to whether it'll be opened up, I'll leave it to others, but you can create a free account on https://cloud.triggermesh.io/ where you can configure your workflow (including your knative service).

**Comment by sebgoa** [comment]
@davidkarlsen if you want to email me at sebgoa@triggermesh.com we can give you access to the SNS sink

**Comment by antoineco** [comment]
@davidkarlsen I'm going to go ahead an close this because I believe the question was answered, feel free to re-open if some input is still needed.

_tl;dr; event "targets" are in a separate repo which is currently closed to the public, but Seb is happy to discuss use cases and provide access._
