### ISSUE TITLE
Add deployment instructions to README

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/aws-event-sources#275]
While instructions for developers are in DEVELOPMENT.md we should have simple `ko` instructions to deploy the controller.

Currently the main readme references using helm, which is not our standard way of deploying.

**Comment by sebgoa** [comment]
we could have both install command: `ko` based and `kubectl apply` but definitely having a single `kubectl apply` would be enough.

**Comment by antoineco** [comment]
Marking as obsolete due to the migration of the code to `triggermesh/triggermesh`.
