### ISSUE TITLE
Add validation to CloudWatch metric query name

### ISSUE THREAD

**Issue by cab105** [triggermesh/aws-event-sources#280]
For context, the metric query name is used by the source to populate the ID field used to identify the query with CloudWatch for follow-up queries and manipulation. The name must adhere to the following regexp as per AWS (https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_MetricDataQuery.html):

    [a-z][a-zA-Z0-9_]*

**Comment by antoineco** [comment]
Tip: the second part can we shortened to `\w*`.

**Comment by cab105** [comment]
Doesn't `\w` include more than alphanumeric?

**Comment by antoineco** [comment]
Regex101.com says 

> \w matches any word character (equivalent to [a-zA-Z0-9_])

I wouldn't have known without it to be honest 😄

**Comment by cab105** [comment]
Wow my memory is getting rusty: https://media.giphy.com/media/83QtfwKWdmSEo/giphy.gif
