### ISSUE TITLE
Inconsistent usage of ARN field

### ISSUE THREAD

**Issue by antoineco** [triggermesh/aws-event-sources#283]
The Performance Insights source asks the user to enter an ARN, but this ARN isn't used for anything except for reading a region to initialize a client. It is possible to pass an ARN for **any AWS service**, and the source would still work. This is very confusing.

The following page suggests that Performance Insights actually uses ARNs to identify real resources:

> `arn:${Partition}:pi:${Region}:${Account}:metrics/${ServiceType}/${Identifier}`
> -- https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsperformanceinsights.html

I suggest we get rid of the `serviceType` and `identifier` attributes and require users to use the ARN format above instead.

@JeffNeff FYI.
I'll try to find time to do it if you don't want to.

**Comment by JeffNeff** [comment]
Why are we removing service type?

**Comment by JeffNeff** [comment]
And identifier... how can we remove that? Its required to make the query

**Comment by antoineco** [comment]
![image](https://user-images.githubusercontent.com/3299086/118723528-d4503f00-b82d-11eb-83b5-eed5f511dd9f.png)

**Comment by antoineco** [comment]
Another option is to use no ARN at all, and simply change `arn` to `region`.
I don't have any preference, both approaches have pros and cons IMO.

**Comment by sebgoa** [comment]
Jeff, I think what Antoine is saying is that we should ask the user to provide the ARN in the spec, using the complete syntax which includes ServiceType and Identifier. If those two parameters are present in the ARN then you don't need them in the spec as separate keys.

**Comment by antoineco** [comment]
Like I said (issue description + my last comment) either that, or rename `arn` to `region`.

**Comment by sebgoa** [comment]
That's what you said but Jeff did not understand it.

**Comment by sebgoa** [comment]
I don't want to bike shed this. I see both sides. 

Bottom line the use of the ARN of the RDS database needs to be better so that the `serviceType` and the `identifier` are computed automatically. the ARN needs to be validated.

Jeff's difficulty was that the PI ARN is indeed not visible from the console.

**Comment by antoineco** [comment]
There is no RDS ARN involved here, the ARN relates to a _metric_.

I acknowledged that this ARN was not obvious in a previous comment and even suggested an alternative: rename `arn` to `region` and only require a region to be passed.

Is that a satisfying conclusion for everyone?
