### ISSUE TITLE
Create Release plan

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/aws-event-sources#32]
* date of release
* change log
* github release bundle
* instructions to install

**Comment by sebgoa** [comment]
on push of git tag we should tag the docker images and make sure we push correctly in GCR.

cc/ @sameersbn

**Comment by sameersbn** [comment]
- https://github.com/triggermesh/aws-event-sources/pull/48 (merged) implemented the ci build setup
 - https://github.com/triggermesh/aws-event-sources/pull/59 (open) includes improvements to the build and ci setup

Together they implement:
 - Github Releases managements
 - Autogenerated Release Notes from Commit History
 - Release notes include links to the binaries
