### ISSUE TITLE
Clean up inactive branches

### ISSUE THREAD

**Issue by antoineco** [triggermesh/aws-event-sources#53]
This repo has a lot of inactive branches. We should review them and delete the ones that are not being worked on anymore.

**Comment by antoineco** [comment]
@sameersbn do you think we can delete this branch? https://github.com/triggermesh/aws-event-sources/commits/circleci-project-setup
It's the last dangling one.

**Comment by sameersbn** [comment]
We already have CircleCI integration so I've deleted it. :+1:

**Comment by antoineco** [comment]
Awesome!
