### ISSUE TITLE
Refactor awsiot source to use Knative's adapter package

### ISSUE THREAD

**Issue by antoineco** [triggermesh/aws-event-sources#83]
Should include necessary changes to Makefile, CI conf, and docs.

To be decided: is it worth rewriting from Python to Go?

**Comment by antoineco** [comment]
@sebgoa it seems like the AWS IoT source remained at the stage of prototype. Right now it's just a piece of Python code lying in its own directory, disconnected from the rest. It's not even mentioned in the README.

I think it's time to decide whether we want to:
* Commit to supporting AWS IoT properly and write a source in Go which is part of our standard release flow
* Remove that code

Any thoughts?

**Comment by benmoss** [comment]
removed in https://github.com/triggermesh/aws-event-sources/pull/300
